source 'http://rubygems.org'
gem 'flay'
gem 'flog'
gem 'mustache'
gem 'rake'
gem 'redis'
gem 'resque'
gem 'ruby_parser'
gem 'rugged'
gem 'shamazing'
gem 'sinatra'
gem 'SystemTimer'
gem 'sprockets'
gem 'yajl-ruby'

group :test do
  gem 'rack-test'
  gem 'redgreen'
  gem 'ruby-debug'
  gem 'mocha'
end