#!/bin/sh
#
# bootstrap

set -e

echo "Setting up your environment..."

#
# Check for Redis
#
if test ! $(which redis-server)
then
  echo "  x You need to install Redis. If you use Homebrew, you can run:"
  echo "    brew install redis"
  exit
fi

#
# Check for Bundler
#
if test ! $(which bundle)
then
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
  exit
fi

#
# Install gems
#
bundle install --binstubs --local --path vendor/gems --without production --quiet

echo "Done!"